latch: "latch, K=2" {
  grid-rows: 3
  grid-columns: 3
  horizontal-gap: 120
  vertical-gap: 90

  H1: "head1()" {
    shape: rectangle
  }
  W1: "w1()" {
    shape: rectangle
    style.fill: lightgreen
  }
  T1: "tail1()" {
    shape: rectangle
  }

  H2: "head2()" {
    shape: rectangle
  }
  W2: "w2()" {
    shape: rectangle
    style.fill: lightgreen
  }
  T2: "tail2()" {
    shape: rectangle
  }

  HC: "head_c()" {
    shape: rectangle
  }
  WAIT: "l.wait()" {
    shape: rectangle
    style.fill: lightgray
  }
  TC: "tail_c()" {
    shape: rectangle
    style.fill: salmon
  }

  H1 -> W1: "Local 1"
  W1 -> T1: "Local 2"

  H2 -> W2: "Local 1"
  W2 -> T2: "Local 2"

  HC -> WAIT: "Local 1"
  WAIT -> TC: "Local 2"

  W1 -> TC
  W2 -> TC: "Latch: w1,w2 < tail_c"
  W1 <-> W2: "w1 || w2" {
    style.stroke-dash: 4
    source-arrowhead.shape: triangle
    target-arrowhead.shape: triangle
  }
}
